version: '3.5'

services:

  dfd-react-app:
    container_name: app-react
    build:
      context: . q
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
